/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import static org.junit.jupiter.api.Assertions.assertEquals;
import org.junit.jupiter.api.Test;

import dam.optativa.DiscountCalculator;

class DiscountCalculatorTest {
    @Test void studentDiscountIsCorrect() {
        assertEquals(DiscountCalculator.calculate(100, true), 20, "student discount should be 20%");
    }

    @Test void noDiscountWithoutStudent() {
        assertEquals(DiscountCalculator.calculate(100, false), 5, "no student discount should be 5%");
    }
    
    @Test void studentDiscountWithDifferentAmount() {
        assertEquals(DiscountCalculator.calculate(50, true), 10, "20% of 50 should be 10");
    }
}


